config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'
  resources :foods
  post '/favorite/:id', to: 'favorites#create', as: :favorites
  delete '/favorite/:id', to: 'favorites#destroy', as: :favorite
  get '/user', to: 'users#index'
  post '/auth/facebook/callback', to: 'facebook#auth_done'
  delete '/', to: 'sessions#destroy'
  get '/login', to: 'users#auth_done'
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
# frozen_string_literal: true

# お気に入りクラス
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates :user_id, :food_id, presence: true
end

app/models/food.rb
# frozen_string_literal: true

# 食材クラス
class Food < ApplicationRecord
  has_many :food_points, dependent: :destroy
  has_many :points, through: :food_points, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :points, presence: { message: 'を選択してください' }

  validates :image, attached: true

  validates :name, length: { maximum: 10 }
  validates :description, length: { maximum: 300 }
  validates :points, length: { maximum: 3, minmum: 1 }

  def self.build_from_params(food_params, point_ids)
    food = Food.new(food_params)
    point_ids.each do |point_id|
      food.points << Point.find(point_id)
    end
    food
  end
end

app/models/food_point.rb
# frozen_string_literal: true

# 食材と見分け方の中間クラス
class FoodPoint < ApplicationRecord
  belongs_to :point
  belongs_to :food
end

app/models/point.rb
# frozen_string_literal: true

# 見分け方クラス
class Point < ApplicationRecord
  has_many :food_points, dependent: :destroy

  validates :point, presence: true
  validates :point, length: { maximum: 20 }
end

app/models/user.rb
# frozen_string_literal: true

# ユーザークラス
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :foods, through: :favorites, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
end

app/controllers/facebook_controller.rb
# frozen_string_literal: true

# Facebook認証コントローラー
class FacebookController < ApplicationController
  def auth_done
    auth = request.env['omniauth.auth']
    user_name = auth[:info][:name]

    # find_or_create_byメソッドが使える
    user = User.find_by(name: user_name) || User.create(name: user_name)
    user.save
    session[:user_id] = user.id

    redirect_to :root
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

# お気に入りコントローラー
class FavoritesController < ApplicationController
  before_action :find_favorite

  def create
    return if @favorite

    Favorite.create(user_id: session[:user_id], food_id: params[:id])
  end

  def destroy
    @favorite.destroy
  end

  private

  def find_favorite
    @favorite = Favorite.find_by(user_id: session[:user_id],
                                 food_id: params[:id])
  end
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

# 食材コントローラー
class FoodsController < ApplicationController
  before_action -> { @points = Point.all }, only: %i[new create]

  def index
    @search = Food.ransack params[:q]
    @result = @search.result

    redirect_to root_path if @result.blank?
    return unless session[:user_id]

    @users_favorite = Favorite.where(user_id: session[:user_id])
  end

  def new
    @food = Food.new
  end

  def create
    point_ids = (params[:point] || []).map { |point| point[:id] }
    @food = Food.build_from_params(food_params, point_ids)

    if @food.save
      flash[:notice] = "#{@food.name}を登録しました"
      redirect_to foods_path
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :description, :image)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# セッションコントローラー
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

# トップページコントローラー
class TopController < ApplicationController
  def index
    @search = Food.ransack params[:q]
    @user_name = User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザーコントローラー
class UsersController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    @favorites = user.foods
  end

  def auth_done
    user_name = 'Test'

    # find_or_create_byメソッドが使える
    user = User.find_by(name: user_name) || User.create(name: user_name)
    user.save
    session[:user_id] = user.id

    redirect_to :root
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# アプリケーションヘルパー
module ApplicationHelper
end

app/helpers/food_helper.rb
# frozen_string_literal: true

# 食材ヘルパー
module FoodHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

# トップページコントローラー
module TopHelper
end

app/views/foods/index.html.erb
<style>
.content_part {
  width: 45%;
  margin-top: 20px;
}

.CatchPhrase_part {
  color: dimgray;
  background-color: lightyellow;
  text-decoration: underline;
  font-weight: bolder;
  font-family: Verdana;
  font-size: 140%;
  text-shadow: 2px 2px 4px lightgray;
}

.favorite_part {
  float: right;
}

.favorite_part_color {
  color: orange;
}

.image_part {
  width: 40%;
  margin: 0;
  float: left;
  margin: 5%;
  border-radius: ;
  box-shadow: 1px 1px 2px black;
}

.image_size {
    display: inline-block;
    height: 160px;
    width: 230px;
}

.point_part {
  margin-top:  20px;
  margin-left: 30px;
  font-size: midium;
  font-weight: bold;
  color: dimgray;
  text-shadow: 2px 2px 4px lightgray;
}

.fa-1x {
  margin-right: 6px;
}

.description_part {
  color: dimgray;
  float: left;
  font-size: small;
  font-family: Verdana;
  font-weight: bolder;
  text-shadow: 1px 1px 2px lightgray;
}

.how_to_title {
  margin-top: 30px;
  color: orange;
  font-family: Verdana;
  font-weight: bolder;
  text-shadow: 1px 1px 2px gold;
}
</style>

<div class="container content_part">
  <ul class="bxslider">
    <% @result.each do |food| %>
      <li>
        <div class="container CatchPhrase_part">
          <%= food.name %>
          <div class="favorite_part">
            <% if session[:user_id] %>
              <% if  @users_favorite.exists?(:food_id => food.id) %>
                <%= link_to favorites_path(food), remote: true, style: 'display: none', method: :post, class: "favorite favorite_part_color" do %>
                  <i class="far fa-star" style="color: orange;"></i>
                <% end %>
                <%= link_to favorite_path(food), remote: true, method: :delete, class: "not_favorite favorite_part_color" do %>
                  <i class="fas fa-star" style="color: orange;"></i>
                <% end %>
              <% else %>
                <%= link_to favorites_path(food), remote: true, method: :post, class: "favorite favorite_part_color" do %>
                  <i class="far fa-star" style="color: orange;"></i>
                <% end %>
                <%= link_to favorite_path(food), remote: true, style: 'display: none', method: :delete, style: 'display: none', class: "not_favorite favorite_part_color" do %>
                  <i class="fas fa-star" style="color: orange;"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="container" style="display: inline-block;">
          <span class="image_part">
            <% if food.image.attached? %>
              <%= image_tag food.image, class: "image_size" %>
            <% end %>
          </span>
          <div style="float: left;">
            <h5 class="how_to_title">美味しい<%= food.name %>の選び方!!</h5>
            <% food.points.each do |point| %>
            <div class="point_part">
              <i class="fas fa-caret-right fa-1x" style="color: orange;"></i><%= point.point %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="container">
          <div class="container description_part">
            <%= food.description %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<!-- slide show  -bxSlider- -->
<script>
jQuery(document).ready(function() {
  jQuery('.bxslider').bxSlider({
    speed: 1000,        // スライドするスピード
    moveSlides: 1,      // 移動するスライド数
    slideWidth: 1000,   // 各スライドの幅
    adaptiveHeight: true,
    infiniteLoop: true, // スライドをループさせるかどうか
    responsive: true,   // レスポンシブ対応
  })

  jQuery('.favorite').on('ajax:success', function() {
    var self = jQuery(this)
    var dislike = self.siblings('.not_favorite')
    self.toggle()
    dislike.toggle()
  })

  jQuery('.not_favorite').on('ajax:success', function() {
    var self = jQuery(this)
    var like = self.siblings('.favorite')
    like.toggle()
    self.toggle()
  })
})
</script>
<script>
  <% if flash[:notice] %>
    alert('<%= flash[:notice] %>');
  <% end %>
</script>
<!-- class Food < Active::Record::base
  has_many :favorites

  def liked_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

- @food.each do |food|
  div
    - if food.liked_by?(current_user)
      星の色あり
    - else
      星の色なし -->

app/views/foods/new.html.erb
<style>

.selected {
  background-color: yellow;
}

.form-control-sm {
  border-width: 1px;
  border-radius: 8px;
  box-shadow: 1px 1px 2px;
  width: 90%;
  margin-left: auto;
  margin-right: auto;
}

.CatchPhrase_part {
  color: darkgray;
  margin-top: 10px;
  margin-left: 30px;
  margin-bottom: -5px;
  font-weight: bolder;
  font-size: 140%;
  font-family: Verdana;
  text-align: left;
  text-shadow: 1px 1px 2px lightgray;
}

.points_part {
  color: darkgray;
  margin-top: 5px;
  margin-left: 30px;
  margin-bottom: -5px;
  font-weight: bolder;
  font-size: 140%;
  font-family: Verdana;
  text-align: left;
  text-shadow: 1px 1px 2px lightgray;
}

.point {
  font-size: 12px;
  color: dimgray;
  font-family: Verdana;
  text-shadow: 1px 1px 2px lightgray;
  border: double lightgray;
  border-radius: 4px;
  box-shadow: 1px 1px 2px;
}

.note_part {
  color: darkgray;
  margin-top: 5px;
  margin-left: 30px;
  margin-bottom: -5px;
  font-weight: bolder;
  font-size: 140%;
  font-family: Verdana;
  text-align: left;
  text-shadow: 1px 1px 2px lightgray;
}

.image_part {
  color: darkgray;
  margin-top: 5px;
  margin-left: 30px;
  margin-bottom: -5px;
  font-weight: bolder;
  font-size: 140%;
  font-family: Verdana;
  text-align: left;
  text-shadow: 1px 1px 2px lightgray;
}

.submit_part {
  color: gray;
  margin-top:10px;
  margin-right: 35px;
  margin-bottom: 20px;
  border-radius: 8px;
  border-width: 1px;
  box-shadow: 1px 1px 2px;
  font-weight: lighter;
  font-size: 100%;
  font-family: Verdana;
  border: outset white;
}

.content_frame {
  background: white;
  border-radius: 50px;
  width: 35%; 
  margin-top: 20px;
  box-shadow: 2px 2px 4px black;
  margin-bottom: 20px;
}

.error_messages {
  color: red;
  margin-left: 20px;
}
</style>

<div class="container content_frame">
<%= form_for @food do |f| %>
  <div class="container">
    <%= f.label :name, 'catch phrase', class: "CatchPhrase_part" %>
    <%= f.text_field :name, class: "form-control form-control-sm" %>
    <div class="error_messages"><%= @food.errors.full_messages_for(:name).inject %></div>
  </div>
  <div class="container" style="text-align: center; margin-top: 10px;">
    <div class="points_part" style="text-align: left">points</div>
    <div class="error_messages" style="text-align: left;"><%= @food.errors.full_messages_for(:points).inject %></div>
    <div class="row" style="margin-right: 15px; margin-left: 15px;">
    <% @points.each_with_index do |point, index| %>
        <div class="point_list col-sm-4">
          <div class="point" style="margin-bottom: 5px; margin-top: 5px; margin-left: -10px; margin-right: -10px;" id="<%= point.id %>"><%= point.point %></div>
        </div>
    <% end %>
    </div>
  </div>
    <div class="container">
      <%= f.label :description, 'note', class: "note_part" %>
      <%= f.text_area :description, class: "form-control form-control-sm" %>
      <div class="error_messages"><%= @food.errors.full_messages_for(:description).inject %></div>
    </div>
    <div class="container">
      <%= f.label :image, 'image', class: "image_part" %>
      <div style="margin-left: 25px">
        <%= f.file_field :image %>
      </div>
      <div class="error_messages"><%= @food.errors.full_messages_for(:image).inject %></div>
    </div>
    <div style="text-align: right;">
      <%= f.submit 'submit', class: "submit_part" %>
<br>
<%= link_to '戻る',root_path , class: "btn btn-light btn-sm buttons" %>

    </div>
<% end %>
</div>
<script>
  var selected_points = new Array() //選択したポイントを格納
  var point_id // 選択したポイントのidを格納
  var input_string // inputタグ生成

  $('.point_list').on('click', 'div', function() {
    if($(this).hasClass('selected')) {
      $(this).removeClass('selected')
      point_id = $(this).attr('id')
      $('input#' + 'point-' + point_id).remove()
      var delete_point = $(this).text()
      selected_points = selected_points.filter(function(point){
        return point !== delete_point
      })
    }else{
      if(selected_points.length < 3) {
        selected_points.push($(this).text())
        $(this).addClass('selected')
        point_id = $(this).attr('id')
        input_string = '<input id="point-' + point_id + '" type="hidden" name="point[][id]" value="' + point_id + '"/>'
        $('form').append(input_string)
      }else{
        alert('登録出来るポイントは３つまでです')
      }
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <style>
  html, body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
  }

  html {
    display: table;
  }

  body {
    background-image: url("/background-image.jpg");
    background-size: cover;
    display: table-cell;
    vertical-align: middle;
  }

  .app_title:hover {
    color: white;
    text-decoration: none;
  }

  .app_title {
    text-decoration: none;
    font-family: cursive, sans-serif;
    color: white;
  }

  .title_style {
    text-align: center;
    text-shadow: 2px 2px 4px gray;
  }
  </style>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">  </head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

  <body>
    <h1 class="title_style"><%= link_to 'Looks yum!', root_path, class: "app_title" %></h1>
    <%= yield %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
  </body>
</html>

app/views/top/index.html.erb
<style>
  .facebook-lg {
     width: 35px;
     height: 35px;
     margin: 10px;
     box-shadow: 2px 2px 4px lightgray;
  }

  .searchform{
    width: 50%;
    border-radius: 3px;
    box-shadow: 1px 1px 2px gray;
  }

  .searchform-style {
    margin-top: 20px;
    margin-bottom: 20px;
    text-align: center;
  }

  .buttons {
    margin: 10px;
    box-shadow: 2px 2px 4px gray;
    font-family: Verdana;
    text-shadow: 1px 1px 2px lightgray;
  }

  .user_name {
    color: white;
    margin-top: 15px;
    text-shadow: 2px 2px 4px gray;
    font-family: Comic Sans MS;
  }
</style>
<div class="container searchform-style">
  <%= search_form_for @search do |f| %>
    <%= f.text_field :name_cont, class: "searchform" %>
    <span style="box-shadow: 2px 2px 4px;">
      <%= f.submit(class: "btn btn-primary") %>
    </span>
  <% end %>
  <% if @user_name %>
    <div class="container user_name">
      <%= @user_name.name %>
    </div>
  <% end %>
  </div>
</div>

<div class="container" style="text-align: center;">
  <% if @user_name %>
    <%= link_to 'My Favorites', user_path, class: "btn btn-light btn-sm buttons" %>
    <%= link_to 'New Knowledge', new_food_path, class: "btn btn-light btn-sm buttons" %>
  <% end %>
  <% unless @user_name %>
    <%= link_to login_path do %>
      <%= image_tag '/facebook-logo.png', class: "facebook-lg" %>
    <% end %>
  <% else %>
    <%= link_to 'logout', root_path, method: :delete, class: "btn btn-light btn-sm buttons" %>
  <% end %>
</div>

app/views/users/index.html.erb
<style>
.content_part {
  width: 45%;
  margin-top: 20px;
}

.CatchPhrase_part {
  color: dimgray;
  background-color: lightyellow;
  text-decoration: underline;
  font-weight: bolder;
  font-family: Verdana;
  font-size: 140%;
  text-shadow: 2px 2px 4px lightgray;
}

.favorite_part {
  float: right;
}

.no_favorite {
  color: white;
  text-decoration: underline;
  text-align: center;
  margin-top: 30px;
  text-shadow: 2px 2px 4px gray;
}

.favorite_part_color {
  color: orange;
}

.image_part {
  width: 40%;
  margin: 0;
  float: left;
  margin: 5%;
  border-radius: ;
  box-shadow: 1px 1px 2px black;
}

/* .image_size {
    display: inline-block;
    height: 100%;
} */

.point_part {
  margin-top:  20px;
  margin-left: 30px;
  font-size: midium;
  font-weight: bold;
  color: dimgray;
  text-shadow: 2px 2px 4px lightgray;
}

.description_part {
  color: dimgray;
  float: left;
  font-size: small;
  font-family: Verdana;
  font-weight: bolder;
  text-shadow: 1px 1px 2px lightgray;
}
</style>
<% unless @favorites.empty? %>
<div class="container content_part">
  <ul class="bxslider">
    <% @favorites.each do |favorite| %>
      <li>
        <div class="container CatchPhrase_part">
          <%= favorite.name %>
          <div class="favorite_part">
            <%= link_to favorite_path(favorite), remote: true, method: :delete, class: "favorite" do %>
              <i class="fas fa-star" style="color: orange;"></i>
            <% end %>
          </div>
        </div>
        <div class="container" style="display: inline-block;">
          <span class="image_size image_part"><%= image_tag favorite.image %></span>
          <div style="float: left;">
            <% favorite.points.each do |point| %>
            <div class="point_part">
              <i class="fas fa-caret-right fa-1x" style="color: orange;"></i>
              <%= point.point %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="container">
          <div class="container description_part">
            <%= favorite.description %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <h4 class="no_favorite">There is no favorites.</h4>
<% end %>
</div>

<!-- slide show  -bxSlider- -->
<script>
jQuery(document).ready(function() {
  jQuery('.bxslider').bxSlider({
    speed: 1000,        // スライドするスピード
    moveSlides: 1,      // 移動するスライド数
    slideWidth: 1000,   // 各スライドの幅
    infiniteLoop: true, // スライドをループさせるかどうか
    responsive: true,   // レスポンシブ対応
  })

  jQuery('.favorite').on('ajax:success', function() {
    window.location.reload()
  })
})
</script>